[package]
name = "geo-test-fixtures"
version = "0.1.0"
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wkt = { version = "0.9", default-features = false }
geo-types = { path = "../geo-types" }
