[package]
name = "geo-types"

version = "0.2.2"
authors = ["Corey Farwell <coreyf@rwell.org>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/georust/geo"
documentation = "https://docs.rs/geo-types/"
readme = "../README.md"
keywords = ["gis", "geo", "geography", "geospatial"]
description = "Geospatial primitive data types"

[dependencies]
num-traits = "0.2"
serde = { version = "1", optional = true, features = ["derive"] }
rstar = { version = "0.1", optional = true }
