[package]
name = "geo"
description = "Geospatial primitives and algorithms"
version = "0.20.1"
license = "MIT/Apache-2.0"
repository = "https://github.com/georust/geo"
documentation = "https://docs.rs/geo/"
readme = "../README.md"
keywords = ["gis", "geo", "geography", "geospatial"]
autobenches = true
edition = "2021"

[features]
use-proj = ["proj"]
proj-network = ["use-proj", "proj/network"]
use-serde = ["serde", "geo-types/serde"]

[dependencies]
float_next_after = "0.1.5"
geo-types = { version = "0.7.4", features = ["approx", "use-rstar"] }
geographiclib-rs = "0.2"
log = "0.4.11"
num-traits = "0.2"
proj = { version = "0.26.0", optional = true }
robust = "0.2.2"
rstar = "0.8"
serde = { version = "1.0", optional = true, features = ["derive"] }

[dev-dependencies]
approx = "0.4.0"
criterion = { version = "0.3", features = ["html_reports"] }
geo-test-fixtures = { path = "../geo-test-fixtures" }
jts-test-runner = { path = "../jts-test-runner" }
pretty_env_logger = "0.4"
rand = "0.8.0"
rand_distr = "0.4.3"

### boolean-ops test deps
anyhow = "1.0.57"
serde = "1.0.137"
serde_json = "1.0.81"
serde_derive = "1.0.137"
glob = "0.3.0"
gt_prev = { version = "0.6.2" , package = "geo-types" }
geo-booleanop = "0.3.2"
wkt = "0.10.1"
geojson = { version = "0.22.3", features = [ "geo-types" ] }

[[bench]]
name = "area"
harness = false

[[bench]]
name = "contains"
harness = false

[[bench]]
name = "convex_hull"
harness = false

[[bench]]
name = "concave_hull"
harness = false

[[bench]]
name = "intersection"
harness = false

[[bench]]
name = "vincenty_distance"
harness = false

[[bench]]
name = "geodesic_distance"
harness = false

[[bench]]
name = "extremes"
harness = false

[[bench]]
name = "euclidean_distance"
harness = false

[[bench]]
name = "rotate"
harness = false

[[bench]]
name = "relate"
harness = false

[[bench]]
name = "simplify"
harness = false

[[bench]]
name = "simplifyvw"
harness = false

[[bench]]
name = "frechet_distance"
harness = false

[[bench]]
name = "rand_line_crossings"
harness = false
